### ISSUE TITLE
最新版小狼毫闪烁，且配色表达异常

### ISSUE THREAD

**Issue by yanhuacuo** [fxliang/weasel_config#1]
录屏：

https://wwqj.lanzoum.com/iCvei0uajwbi

之前调过一个配色，是这样的：

```
  amber-2:
    name: 琥珀-新绿／Amber-green
    author: 五笔小筑 <wubixiaozhu@126.com>
    text_color: 0xffffff #默认文字颜色
    back_color: 0x72D4BD #候选窗背景色
    border_color: 0x00444444 #候选窗边框颜色
    candidate_back_color: 0x72D4BD #非高亮候选背景颜色    
    comment_text_color: 0xffffff #opencc注解颜色
    candidate_shadow_color: 0x00000000 #非高亮候选背景块阴影颜色
    candidate_text_color: 0xffffff #非高亮候选文字颜色
    label_color: 0xffffff #非高亮候选序数值颜色
    hilited_candidate_border_color: 0xc227BA53 #高亮候选背景块描边色
    hilited_candidate_shadow_color: 0xabD41789 #高亮候选背景块阴影颜色
    hilited_label_color: 0xffffff #高亮候选的序数值颜色
    hilited_mark_color: 0xDE33C1 #标记高亮的标签小竖块的颜色
    hilited_shadow_color: 0xab2EFF58 #编码背景块阴影颜色
    hilited_text_color: 0x82e6ca #编码文字颜色
    hilited_back_color: 0x27BA53 #编码背景颜色
    hilited_candidate_text_color: 0xffffff #高亮候选文字颜色
    hilited_candidate_back_color: 0xc227BA53 #高亮候选背景颜色
    shadow_color: 0xab2EFF58 #候选窗阴影色，默认全透明（无阴影）
```

![pic](https://raw.githubusercontent.com/yanhuacuo/css/master/weasel-11.png)

但是，现在最新版中，它成了这样：

![PIC](https://raw.githubusercontent.com/yanhuacuo/css/master/b.png)

另一款：

```
  98wb-pink:
    name: 一品红／98wb-pink
    author: 五笔小筑 <wubixiaozhu@126.com>
    text_color: 0xffffff #默认文字颜色
    back_color: 0xabE8CB3C #候选窗背景色
    border_color: 0xE8CB3C #候选窗边框颜色
    candidate_back_color: 0x00000000 #非高亮候选背景颜色    
    comment_text_color: 0xffffff #opencc注解颜色
    label_color: 0xffffff #非高亮候选序数值颜色
    candidate_shadow_color: 0x00000000 #非高亮候选背景块阴影颜色
    candidate_text_color: 0xffffff #非高亮候选文字颜色
    hilited_candidate_border_color: 0xE82EE8 #高亮候选背景块描边色
    hilited_candidate_shadow_color: 0xab13E8E8 #高亮候选背景块阴影颜色
    hilited_label_color: 0xffffff #高亮候选的序数值颜色
    hilited_mark_color: 0xDE33C1 #标记高亮的标签小竖块的颜色
    hilited_shadow_color: 0xab187BDD #编码背景块阴影颜色
    hilited_text_color: 0x82e6ca #编码文字颜色
    hilited_back_color: 0x42BA2CDD #编码背景颜色
    hilited_candidate_text_color: 0xffffff #高亮候选文字颜色
    hilited_candidate_back_color: 0xa1E82EE8 #高亮候选背景颜色
    shadow_color: 0xab13E868 #候选窗阴影色，默认全透明（无阴影）
```

以前是这样：

![PIC](https://raw.githubusercontent.com/yanhuacuo/css/master/01.png)

现在成了这样：

![PIC](https://raw.githubusercontent.com/yanhuacuo/css/master/c.png)

再如：

```
  sakura:
    name: 樱花／sakura
    author: 空山明月 <sqqlove123@163.com>
    text_color: 0x7264D3
    back_color: 0xEBE1F6
    border_color: 0x8C7CDB
    candidate_back_color: 0xEBE1F6
    comment_text_color: 0x7264D3
    hilited_comment_text_color: 0x2B2270
    label_color: 0x7264D3
    hilited_label_color: 0x2B2270
    hilited_mark_color: 0x2B2270
    hilited_text_color: 0x2B2270
    hilited_back_color: 0xC4BEF0
    hilited_candidate_text_color: 0x2B2270
    hilited_candidate_back_color: 0xC4BEF0
    shadow_color: 0x6b000000
    hilited_shadow_color: 0x6b000000  
    # hilited_candidate_border_color: 0x141620
    hilited_candidate_shadow_color: 0x6b000000
```

正常应该是：

![PIC](https://raw.githubusercontent.com/yanhuacuo/css/master/cd.jpg)

但现在变成了：

![PIC](https://raw.githubusercontent.com/yanhuacuo/css/master/a.png)

**Comment by yanhuacuo** [comment]
闪烁的问题，在录屏的链接中。
配色表达前后差异的问题，见上述。
主要是「候选框背景色」发生了变化，且阴影消失了（请求加回来）

**Comment by fxliang** [comment]
没有删除阴影，而是根据和相关大神沟通，纷纷表示back后的阴影都应该clip掉才符合现代ui的风格，所以目前back下方没有阴影clip掉了。闪烁目前没有发现。

**Comment by yanhuacuo** [comment]
> 没有删除阴影，而是根据和相关大神沟通，纷纷表示back后的阴影都应该clip掉才符合现代ui的风格，所以目前back下方没有阴影clip掉了。闪烁目前没有发现。

可以考虑做个参数开关吗？阴影带来的细腻感，在高分屏下，与MacOS 默认的窗口效果一样好。

现在的改动，导致之前做的配色全部失效了：

https://zhuanlan.zhihu.com/p/615355227

**Comment by yanhuacuo** [comment]
> 没有删除阴影，而是根据和相关大神沟通，纷纷表示back后的阴影都应该clip掉才符合现代ui的风格，所以目前back下方没有阴影clip掉了。闪烁目前没有发现。

闪烁感很严重，可以看一下链接中的录屏，系统是 win11

**Comment by fxliang** [comment]
> > 没有删除阴影，而是根据和相关大神沟通，纷纷表示back后的阴影都应该clip掉才符合现代ui的风格，所以目前back下方没有阴影clip掉了。闪烁目前没有发现。
> 
> 可以考虑做个参数开关吗？阴影带来的细腻感，在高分屏下，与MacOS 默认的窗口效果一样好。
> 
> 现在的改动，导致之前做的配色全部失效了：
> 
> https://zhuanlan.zhihu.com/p/615355227

没有取消阴影，你的配色在我这边试也没有问题，你应该检查你配置哪里修改了东西冲突了。
![image](https://user-images.githubusercontent.com/4023160/236081006-3388c134-2feb-486d-9193-fd38689b3b10.png)

**Comment by fxliang** [comment]
> > 没有删除阴影，而是根据和相关大神沟通，纷纷表示back后的阴影都应该clip掉才符合现代ui的风格，所以目前back下方没有阴影clip掉了。闪烁目前没有发现。
> 
> 可以考虑做个参数开关吗？阴影带来的细腻感，在高分屏下，与MacOS 默认的窗口效果一样好。
> 
> 现在的改动，导致之前做的配色全部失效了：
> 
> https://zhuanlan.zhihu.com/p/615355227

![image](https://user-images.githubusercontent.com/4023160/236099557-cc1e11c2-969e-4b70-9afd-9333582612c6.png)
clip掉back下的阴影的效果大概是这个样子（back_color色块正下方的shadow_color不绘制），这个不影响颜色解析的。相关的修改在 [这里](https://github.com/fxliang/weasel/blob/master/WeaselUI/WeaselPanel.cpp#L395-L400)，不想要这个clip的话，只要将399行外的代码注释了就可以

新近修改的是将hex编码表示的颜色限定在三位，四位，六位，八位（参照css的颜色展开逻辑），这个在你给出的颜色中也未见有例外的设定，颜色支持默认的abgr/argb/rgba的序列，但是你给出的设置也没有设置对应配色方案的color_format，就会默认是abgr的序列，这个也不会影响颜色的解析。具体见 [这里](https://github.com/fxliang/weasel/blob/master/RimeWithWeasel/RimeWithWeasel.cpp#L672-L720)

未知你在用的是不是另外98小组修改的状态会有其他的修改可能有影响 ？

另外在你给出的专栏的回复中你回复的内容，这个透明色使用的是gdi+的处理，不存在win10无效只有 win11有效这种情况。

还有一个信息是，你专栏中的这个整体设定会让使用的配色的back_color如果alpha不在0x01-0x7f内自动设置成0x7f，还有就是会强制禁用窗口外阴影。这个策略是因为style/blur_window是为毛玻璃而存在的，对应使用到的系统API限制要求外阴影不绘制&back_color 的alpha 在01~7f之间。<del>因此新修订的版本中允许在配色中设置这个blur_window的值，这样可以多个配色之间不相互影响。</del>具体见 [这里](https://github.com/fxliang/weasel/blob/master/RimeWithWeasel/RimeWithWeasel.cpp#L981-L997)


```yaml
style:
  blur_window: true
```

**Comment by yanhuacuo** [comment]
感谢解释，去除了「blur_window」这行参数之后，之前写的几十款配色的大体模样恢复了。
但是，颜色的色相发生了变化。

编码区背景色、首候选项背景色、整体输入框背景色，都发生了变化。

已经去除掉 `blur_window` 后，依然发生这种色相变化，是因为透明度通道的原因吗？

```
back_color如果alpha不在0x01-0x7f内自动设置成0x7f
```

基于 [这份 weasel.yaml](https://github.com/yanhuacuo/css/blob/master/weasel.yaml)  

渲染结果如下：

![PIC](https://raw.githubusercontent.com/yanhuacuo/css/master/pic/2023-05-08_232311.png)


示例配色是这份：

```
  98wb-pink:
    name: 一品红／98wb-pink
    author: 五笔小筑 <wubixiaozhu@126.com>
    text_color: 0xffffff #默认文字颜色
    back_color: 0xabE8CB3C #候选窗背景色
    border_color: 0xE8CB3C #候选窗边框颜色
    candidate_back_color: 0x00000000 #非高亮候选背景颜色    
    comment_text_color: 0xffffff #opencc注解颜色
    label_color: 0xffffff #非高亮候选序数值颜色
    candidate_shadow_color: 0x00000000 #非高亮候选背景块阴影颜色
    candidate_text_color: 0xffffff #非高亮候选文字颜色
    hilited_candidate_border_color: 0xE82EE8 #高亮候选背景块描边色
    hilited_candidate_shadow_color: 0xab13E8E8 #高亮候选背景块阴影颜色
    hilited_label_color: 0xffffff #高亮候选的序数值颜色
    hilited_mark_color: 0xDE33C1 #标记高亮的标签小竖块的颜色
    hilited_shadow_color: 0xab187BDD #编码背景块阴影颜色
    hilited_text_color: 0x82e6ca #编码文字颜色
    hilited_back_color: 0x42BA2CDD #编码背景颜色
    hilited_candidate_text_color: 0xffffff #高亮候选文字颜色
    hilited_candidate_back_color: 0xa1E82EE8 #高亮候选背景颜色
    shadow_color: 0xab13E868 #候选窗阴影色，默认全透明（无阴影）
```


98小组没有改动源码，只是做了拉取编译，然后由于是这样分发可执行包，没那么多顾虑（不需与官方版本的文件一致），就把所有应该生效的参数整理到了[这份 weasel.yaml](https://github.com/yanhuacuo/css/blob/master/weasel.yaml) 中。

然后大家做了几十款配色，现在都面目全非了，就没有继续追新。

盼复。
