### ISSUE TITLE
 vertical相关参数不生效

### ISSUE THREAD

**Issue by yanhuacuo** [fxliang/weasel_config#3]
在 weasel.yaml 中直接配置  vertical 相关参数：

[  vertical_text: false
  vertical_text_left_to_right: false
  vertical_text_with_wrap: false
](https://github.com/yanhuacuo/weasel-data/blob/1118d4d4bafc14a4812a5c62a13ef59f7d4505d8/Rime/weasel.yaml#L42-L44)

发现并不生效，查 log 也没有看到任何报错或警告，配置文件如下，请求支援：

https://github.com/yanhuacuo/weasel-data

**Comment by yanhuacuo** [comment]
`bool` 值改为 `true` 时，部署后无反应，观察 build ，也有参数的正确表达，log 无异常信息。

**Comment by fxliang** [comment]
你想怎么生效
我看来表现正常的呀

```yaml
patch: 
  __include:  _vertical_text_

_vertical_text_:
  vertical_text: false
  vertical_text_left_to_right: false
  vertical_text_with_wrap: false
```

部署之后
![image](https://github.com/fxliang/weasel_config/assets/4023160/9987f50f-8ccc-4100-bf78-bb3c33864fb5)
挺正常的

三个值改为true之后
![image](https://github.com/fxliang/weasel_config/assets/4023160/e33c735e-3bf3-4dc6-9167-8ab2044c141c)
